- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Wave1
  # - Atlas
  # - Bagel
  # - Box
  # - Cluster
  # - Core
  # - Fland
  # - Marathon
  # - Meta
  # - Omega
  # - Origin
  # - Saltern
  # - Packed
  # - Reach
  #- Train <- return after station anchoring PR is finished and merged
